# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='group_id',
            field=models.PositiveIntegerField(verbose_name='分组id'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='permission_id',
            field=models.PositiveIntegerField(verbose_name='权限id'),
        ),
        migrations.AlterField(
            model_name='userextendinfo',
            name='user_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_id',
            field=models.PositiveIntegerField(verbose_name='分组id'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user_id',
            field=models.PositiveIntegerField(verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission_id',
            field=models.PositiveIntegerField(verbose_name='权限id'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='user_id',
            field=models.PositiveIntegerField(verbose_name='用户id'),
        ),
    ]
