# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180115_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentType',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='content_type_id',
        ),
        migrations.AddField(
            model_name='permission',
            name='desc',
            field=models.CharField(default='描述', max_length=200, verbose_name='权限描述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='权限名'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_id',
            field=models.PositiveIntegerField(verbose_name='分组/角色id'),
        ),
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together=set([('group_id', 'permission_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together=set([('user_id', 'group_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together=set([('user_id', 'permission_id')]),
        ),
    ]
