# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180116_1042'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='group',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='grouppermission',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='permission',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userextendinfo',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usergroup',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userpermission',
            managers=[
            ],
        ),
    ]
